# Number Guessing Game using Python

import time
import random
import math

def type_out(text, delay=0.03):
    for char in text:
        print(char, end="", flush=True)  
        time.sleep(delay) 
    print()  

def game(no_to_guess, chances):
    counter = 0
    answer = no_to_guess

    while counter < chances:
        counter+=1

        try:
            user_guess = int(input("Guess the number within your range : "))
        except ValueError:
            print("Invalid input! Please enter a valid number.")
            guess_counter -= 1  # Don't count invalid attempts
            continue

        if user_guess == answer:
            type_out("Your guess is correct.")
            type_out("Congratulations!!  You won the game :)")
            break
        elif user_guess > answer:
            type_out("Your guess is too High! Please try again.")
        elif user_guess<answer:
            type_out("Your guess is too Low! Please try again.")
        elif counter>=chances and user_guess!=answer:
            type_out("Oops!! You ran out of chances:( ")
            type_out("Game Over! Better Luck next time.")



def main():
    print()
    print("--------------------------------------------------------------------------------------")
    print()
    
    type_out("Hello there! I'm your assistant.")
    type_out("let's play a number guessing game.")
    type_out("In this game, you first have to select an integer range.")
    type_out("Then you have to guess the correct no. generated by the computer :)")
    type_out("See it's so simple!! Let's Start.")
    
    print()
    print("--------------------------------------------------------------------------------------")
    print()
    
    lb = int(input("Enter the lower bound of your number range: "))
    ub = int(input("Enter the upper bound of your number range: "))

    res = ub-lb+1
    chances = math.ceil(math.log2(res))

    type_out(f"You will get {chances} no. of guesses.")

    
    no_to_guess = random.randrange(lb, ub+1)

    game(no_to_guess, chances)

    print()
    print("--------------------------------------------------------------------------------------")
    print()


if __name__ == "__main__":
    main()
